version: '3.8'

services:
  web:
    build: .
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
      - /app/node_modules
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"  # Limit the log size to 10MB
